# GitHub Pages Configuration
theme: minima

# Include JSON data files
include:
  - "data/*.json"

# Exclude development files
exclude:
  - "*.py"
  - "__pycache__/"
  - "fasttext/*.npy"
  - "extract/"
  - "convert_data.py"
  - "server.py"
  - "main.py"